"""Add structure field to BaseDocument

Revision ID: 09f93edb554c
Revises: 409b9558a51f
Create Date: 2025-10-25 16:55:49.432378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09f93edb554c'
down_revision: Union[str, None] = '409b9558a51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_document', sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_document', 'structure')
    # ### end Alembic commands ###
